Rebase ElectrumG to the latest upstream version
BTCGPU/electrum pull request #58
Opened 2021-05-17 12:51 UTC by R-Santev

## Motivation

ElectrumG was not recently updated and it's good to have the latest features and bug fixes from electrum. That's why I have rebased the wallet to the latest master of electrum.

## Implementation

The rebase process included multiple conflicts and therefore this branch is recommended to be merged by force push to master as it is rebased.

2021-05-17 12:52 UTC, h4x3rotab commented
Could you rebase to upstream/master?

```bash
git fetch upstream
git rebase upstream/master
git push --force
```

2021-05-23 08:31 UTC, h4x3rotab requested changes

2021-05-23 08:31 UTC, h4x3rotab commented on contrib/build-wine/electrum.nsi
> +  !define PRODUCT_PUBLISHER "BitcoinGold Team"
"The BTG Organization"

2021-05-23 08:31 UTC, h4x3rotab commented on contrib/build-wine/electrum.nsi
> +  WriteRegStr HKCU "Software\Classes\bitcoing\shell\open\command" "" "$\"$INSTDIR\electrumg-${PRODUCT_VERSION}.exe$\" $\"%1$\""
Check btg core register path

2021-05-23 08:31 UTC, h4x3rotab commented on contrib/build-wine/sources.list.aliyun
> +deb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
Plz remove this file. It shouldn't be used

2021-05-23 08:31 UTC, h4x3rotab commented on contrib/deterministic-build/requirements-hw.txt
> +    --hash=sha256:df277cb51e61359aba502208d680f90c0493adec6f0e848af94948778aed386e
If no good reason, let's stick to the upstream version (they are also newer)

2021-05-23 08:31 UTC, h4x3rotab commented on contrib/requirements/requirements.txt
> +dnspython
Let's keep dnspython the same as the upstream (move to the bottom, and keep the comments)

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/base_wizard.py
> +            # ('2fa', _("Wallet with two-factor authentication")),
```suggestion
            # TODO: fix the 2fa
            # ('2fa', _("Wallet with two-factor authentication")),
```

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/blockchain.py
> +        return self.check_hash(height, header_hash)
Remove trailing spaces

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/blockchain.py
> +
Spaces

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/constants.py
> +GIT_ISSUE_URL = GIT_REPO_URL + "/issues"
```suggestion
GIT_REPO_ISSUES_URL = GIT_REPO_URL + "/issues"
```

And change the other files as well. This will be good for us to keep sync with the upstream

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/gui/kivy/main_window.py
> +        self.address_screen = None
Are they still in use? If not, let's remove them

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/gui/qt/main_window.py
> +            f'''<a href="{constants.GIT_ISSUE_URL}">{constants.GIT_ISSUE_URL}</a><br/><br/>''',
GIT_REPO_ISSUE_URL

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/lnaddr.py
> +            wprog = u5_to_bitarray(witness[1:])
Let's rollback to the upstream's implementation

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/transaction.py
> +            nSequence = int_to_hex(0xfffffffd, 4)
I think this is incorrect. Let's roll back to the upstream version and check if tx singing works

2021-05-23 08:31 UTC, h4x3rotab commented on electrum/blockchain.py
> +    def fork(self, parent, header: dict) -> 'Blockchain':
```suggestion
    def fork(parent, header: dict) -> 'Blockchain':
```

2021-05-26 10:53 UTC, R-Santev commented on electrum/transaction.py
> +            nSequence = int_to_hex(0xfffffffd, 4)
I changed it and it's working.

2021-05-30 16:17 UTC, h4x3rotab commented on electrum/lnaddr.py
> +        if wver is not None:
Trailing spaces

2021-05-30 16:19 UTC, h4x3rotab commented on electrum/transaction.py
> +        sighash = txin.sighash | SIGHASH_ALL | constants.net.SIGHASH_FORK_BTG
Let's switch back to the original impl, and always add `constants.net.SIGHASH_FORK_BTG` to the sighash flag

2021-06-02 07:22 UTC, merged